### ISSUE TITLE
Cannot use GPU in CPU-only Caffe

### ISSUE THREAD

**Issue by mkhademi** [yjxiong/caffe#82] opened 2016-06-06 18:11 UTC
Hi @yjxiong @wanglimin 

I already got some results compiling caffe under CPU_ONLY mode. Later, I switched to GPU mode by doing a make clean, commenting in the "CPU_ONLY := 1" line in Makefile.config and was able to successfully compile caffe with GPU mode. However, when I run demo.py, it keeps giving me the following error:

[Caffe:F0607 15:03:58.027321 28444 common.cpp:66] Cannot use GPU in CPU-only Caffe: check mode.
**\* Check failure stack trace: ***

BTW, I have a single GPU. Here are the lines specifying gpu_id and setting the mode to gpu in my demo.py:

gpu_id = 0
caffe.set_device(gpu_id)
caffe.set_mode_gpu()

Am I missing something?

Thanks!

**Comment by yjxiong** [comment] 2016-06-07 07:18
I am afraid that you have to set GPU mode before setting device.

**Comment by mkhademi** [comment] 2016-06-07 18:36
@yjxiong I switched the lines as you suggested (see below) but it did not work! 

gpu_id = 0
caffe.set_mode_gpu()
caffe.set_device(gpu_id)

Anything else you can think of? Other than makefile.config and these lines in demo.py, is there anything else I need to adjust before being able to run the code under GPU?

Thanks!

**Comment by yjxiong** [comment] 2016-06-08 02:00
Just noticed the message says "Cannot use GPU in CPU-only Caffe". This means your build is still in the CPU-only configuration. Please check your building process. Actually as README states, I suggest using CMake to do the compilation. We are not maintaining the Makefile in this repo.

**Comment by mkhademi** [comment] 2016-06-08 17:46
@yjxiong @wanglimin Thanks for your reply! I also did a make clean and used cmake per your suggestion. The compilation went through successfully but then when I ran my "demo.py", the error showed up again! I believe my build is done with GPU correctly because I can see it goes through all the .cu files during "make all".

Could you think of anything else I am missing?

Thanks!

**Comment by yjxiong** [comment] 2016-06-10 04:06
I don't know what exactly the problem is. Here is some advices I can think of.
1. Check the linked `libcaffe.so` for your python interfaces' `_caffe.so`. it might use an older version with CPU-only build.
2. Make sure you can use `nvidia-smi` to list your GPUs. This guarantees that the driver is working properly.
3. Try compile and run CUDA examples to make sure the CUDA is working properly.

Hope these could help.

**Comment by yjxiong** [comment] 2016-06-15 04:08
Any progress? @mkhademi

**Comment by mkhademi** [comment] 2016-06-17 20:01
@yjxiong Sorry for the delay! Back to your suggestions, as I mentioned before, I previously made sure that my CUDA installation is working properly! So #2 and #3 were checked already! For #1, I made sure when I make caffe clean, there is no _caffe.so in python/caffe folder and then when I do make pycaffe, it generates a new version of that. But I am still getting the same error!

**Comment by yjxiong** [comment] 2016-08-08 06:07
Hi @mkhademi !

Have you figured out the issue?

**Comment by mkhademi** [comment] 2016-08-08 17:39
Hi @yjxiong,

Since my other machine was working fine with GPU, I did not spend any more time fixing this issue. I think we can close the issue for now. If I happen to know what the problem is in future, I will definitely update here.

**Comment by yjxiong** [comment] 2016-08-09 01:54
Sure. Closing this. 
Please do let me know if you find the problem :)

**Closed as completed by yjxiong** 2016-08-09 01:54 UTC
