### ISSUE TITLE
make error：libunwind.so.8: undefined reference to 'lzma_index_size@XZ_5.0'

### ISSUE THREAD

**Issue by applesleam** [yjxiong/caffe#138] opened 2017-01-30 06:39 UTC
Hi @yjxiong ,

Thank you so much for your hard work on this project. I'm very interested in your code. I `cmake .. -DUSE=ON` successfully, but as I running the command `make && make install` I encountered the following errors：
```
~/Git/caffe/build$ make
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   system
--   thread
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Found PROTOBUF Compiler: /usr/bin/protoc
-- Found lmdb    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/liblmdb.so)
-- Found LevelDB (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libleveldb.so)
-- Found Snappy  (include: /usr/include, library: /usr/lib/libsnappy.so)
-- CUDA detected: 7.5
-- Found cuDNN (include: /usr/local/include, library: /usr/local/lib/libcudnn.so)
-- Added CUDA NVCC flags for: sm_52
-- OpenCV found (/home/sdy/anaconda2/share/OpenCV)
-- Found Atlas (include: /usr/local/include, library: /usr/lib/libatlas.so)
-- NumPy ver. 1.11.2 found (include: /home/sdy/anaconda2/lib/python2.7/site-packages/numpy/core/include)
-- Could NOT find Boost
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Python interface is disabled or not all required dependecies found. Building without it...
-- 
-- ******************* Caffe Configuration Summary *******************
-- General:
--   Version           :   <TODO> (Caffe doesn't declare its version in headers)
--   Git               :   v0.9999-1620-gb065585-dirty
--   System            :   Linux
--   C++ compiler      :   /usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release
-- 
--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   ON
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   ON
--   CPU_ONLY          :   OFF
-- 
-- Dependencies:
--   BLAS              :   Yes (Atlas)
--   Boost             :   Yes (ver. 1.54)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 2.5.0)
--   lmdb              :   Yes (ver. 0.9.10)
--   Snappy            :   Yes (ver. 1.1.0)
--   LevelDB           :   Yes (ver. 1.15)
--   OpenCV            :   Yes (ver. 2.4.11)
--   CUDA              :   Yes (ver. 7.5)
-- 
-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_52
--   cuDNN             :   Yes
-- 
-- Documentaion:
--   Doxygen           :   No
--   config_file       :   
-- 
-- Install:
--   Install path      :   /home/sdy/Git/caffe/build/install
-- 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sdy/Git/caffe/build
[  1%] Built target proto
Scanning dependencies of target caffe
Linking CXX shared library ../../lib/libcaffe.so
[ 91%] Built target caffe
Linking CXX executable caffe
//usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to `lzma_index_size@XZ_5.0'
//usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to `lzma_stream_footer_decode@XZ_5.0'
//usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to `lzma_index_uncompressed_size@XZ_5.0'
//usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to `lzma_stream_buffer_decode@XZ_5.0'
//usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to `lzma_index_buffer_decode@XZ_5.0'
//usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to `lzma_index_end@XZ_5.0'
collect2: error: ld returned 1 exit status
make[2]: *** [tools/caffe] Error 1
make[1]: *** [tools/CMakeFiles/caffe.bin.dir/all] Error 2
make: *** [all] Error 2
```

I've tried to reinstall libunwind with `apt-get install libunwind8-dev`, but the error is still unsolved.
My system is Ubuntu  14.04.5 LTS with CUDA-7.5 and Cudnn-5.
Thanks a lot and looking for your reply！Happy Chinese New Year！

**Comment by yjxiong** [comment] 2017-02-02 14:36
Usually, this kind of errors is caused by multiple versions of some libraries installed on your machine, instead of some missing library. And the mislinked library may even not be `lzma` itself. 

So please have a look on whether you have this issue before further analysis.

**Comment by applesleam** [comment] 2017-02-02 14:49
Thank you @yjxiong ! In the former step of `cmake`, there didn't have any warning or error. I wil check the probable issue you mentioned and try to figure it out. Thanks again!

**Comment by yjxiong** [comment] 2017-02-14 09:46
@applesleam any luck with this?

**Comment by applesleam** [comment] 2017-02-14 11:27
Sorry for replying so late @yjxiong , I was interrupt by other task previous days. During another task I upgrade CUDA7.5 on my computer to CUDA8.0 and cuDNN5.0 to cuDNN5.1, but problem still remains the same.
Also I've tried to add `export LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu/"` in ~/.bashrc like this [issue](https://github.com/BVLC/caffe/issues/3814), but it didn't work to me. I will try to check the versions of other libraries as you said.
 Thank you so much!

I pasete the log of `cmake .. -DUSE_MPI=ON` below, in case there probably has some potential prolems that I'm not able to find out.
```
~/Git/caffe/build$ cmake .. -DUSE_MPI=ON
-- The C compiler identification is GNU 4.9.4
-- The CXX compiler identification is GNU 4.9.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   system
--   thread
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found GFlags: /usr/include  
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found Glog: /usr/include  
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Found PROTOBUF: /usr/lib/x86_64-linux-gnu/libprotobuf.so  
-- Found PROTOBUF Compiler: /usr/bin/protoc
-- Found HDF5: /usr/lib/x86_64-linux-gnu/libhdf5_hl.so;/usr/lib/x86_64-linux-gnu/libhdf5.so  
-- Found LMDB: /usr/include  
-- Found lmdb    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/liblmdb.so)
-- Found LevelDB: /usr/include  
-- Found LevelDB (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libleveldb.so)
-- Found Snappy: /usr/include  
-- Found Snappy  (include: /usr/include, library: /usr/lib/libsnappy.so)
-- CUDA detected: 8.0
-- Found cuDNN (include: /usr/local/include, library: /usr/local/lib/libcudnn.so)
-- Added CUDA NVCC flags for: sm_52
-- OpenCV found (/home/sdy/anaconda2/share/OpenCV)
-- Found Atlas: /usr/local/include  
-- Found Atlas (include: /usr/local/include, library: /usr/lib/libatlas.so)
-- Found PythonInterp: /home/sdy/anaconda2/bin/python2.7 (found suitable version "2.7.11", minimum required is "2.7") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable version "2.7.6", minimum required is "2.7") 
-- Found NumPy: /home/sdy/anaconda2/lib/python2.7/site-packages/numpy/core/include (found suitable version "1.11.2", minimum required is "1.7.1") 
-- NumPy ver. 1.11.2 found (include: /home/sdy/anaconda2/lib/python2.7/site-packages/numpy/core/include)
-- Could NOT find Boost
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Found MPI_C: /usr/lib/libmpi.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libhwloc.so  
-- Found MPI_CXX: /usr/lib/libmpi_cxx.so;/usr/lib/libmpi.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libhwloc.so  
-- Python interface is disabled or not all required dependecies found. Building without it...
-- Found Git: /usr/bin/git (found version "1.9.1") 
-- 
-- ******************* Caffe Configuration Summary *******************
-- General:
--   Version           :   <TODO> (Caffe doesn't declare its version in headers)
--   Git               :   v0.9999-1620-gb065585-dirty
--   System            :   Linux
--   C++ compiler      :   /usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release
-- 
--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   ON
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   ON
--   CPU_ONLY          :   OFF
-- 
-- Dependencies:
--   BLAS              :   Yes (Atlas)
--   Boost             :   Yes (ver. 1.54)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 2.5.0)
--   lmdb              :   Yes (ver. 0.9.10)
--   Snappy            :   Yes (ver. 1.1.0)
--   LevelDB           :   Yes (ver. 1.15)
--   OpenCV            :   Yes (ver. 2.4.11)
--   CUDA              :   Yes (ver. 8.0)
-- 
-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_52
--   cuDNN             :   Yes
-- 
-- Documentaion:
--   Doxygen           :   No
--   config_file       :   
-- 
-- Install:
--   Install path      :   /home/my_usr_name/Git/caffe/build/install
-- 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/my_usr_name/Git/caffe/build
```

**Comment by yjxiong** [comment] 2017-02-15 06:22
I can see no problem from your log. Did you try removing all files under `build/` and start again? And to make sure, you may try start without MPI support.

**Comment by applesleam** [comment] 2017-02-15 06:54
Yes, each time I remove `build/` and start over again, and I tried `cmake .. -DUSE_MPI=OFF` which turned out to be the same error.

**Comment by yjxiong** [comment] 2017-02-15 07:45
My guess is still that you may have mislinked libraries. So please try checking any library which you have multiple versions of it installed.

**Comment by applesleam** [comment] 2017-02-16 11:28
Hi @yjxiong , I solved this problem by simply commenting the `export PATH="/home/my_usr_name/anaconda2/bin:$PATH"` in ~/.bashrc as this [issue](https://github.com/BVLC/caffe/issues/3814) said. This issue said it might be caused by anaconda 3rd library dependency problem. Frankly, I don't really understand why this happened as a beginner to caffe  :(
Thank you very very very much for helping me!

**Comment by yjxiong** [comment] 2017-02-16 12:07
@applesleam Good to know. 
Now it makes sense. Anaconda packaged a bunch of 3rd-party libraries in the form of `so` files, to form a battery included distribution. 

Because its bin path is at the head of your `PATH` variable, CMake will definitely invoke its Python binary to determine the path of Python libraries for building Python interfaces and put it in the linker's path. The tricky thing is that those 3rd-party libs are also under the same directory. They will thus override your system's libraries during linking. So you will meet the observed problem due to the mismatch between headers and the libraries being linked.

Closing this issue. Please feel free to reopen it if you meet any further problem. And many thanks for posting your solutions.

**Closed as completed by yjxiong** 2017-02-16 12:07 UTC
